name: translate
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dartx: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  language_detector: ^1.0.1
  rename_app: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/translate.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/translate.png

flutter:
  uses-material-design: true
